### ISSUE TITLE
I believe punycode.decode("ls8h=") should be an error

### ISSUE THREAD

**Issue by domenic** [mathiasbynens/punycode.js#129]
I don't know the actual punycode algorithm, but based on the URL Standard test cases expecting `https://xn--ls8h=/` to be an error, and jsdom/whatwg-url not passing this, I think the issue is with Punycode. `punycode.decode("ls8h=")` gives me `"💧💩"` instead of erroring.

/cc @karwa who seems to have enough of the Punycode algorithm in their head to be able to contribute fixes, potentially 🙏

**Comment by karwa** [comment]
I think I fixed this already 😊 - https://github.com/mathiasbynens/punycode.js/pull/124

When I try it on the RunKit NodeJS playground, the example does throw an error: https://runkit.com/embed/2b1uqmww0euj

**Comment by domenic** [comment]
Hmm, I was pretty sure I had updated my dependencies, but I guess not!
