### ISSUE TITLE
Missing releases. Missing tag for `punycode@2.3.0`.

### ISSUE THREAD

**Issue by MikeMcC399** [mathiasbynens/punycode.js#131]
Please add the releases after `2.0.0` to the GitHub releases section.

At the moment https://github.com/mathiasbynens/punycode.js/releases contains only

- [v2.0.0](https://github.com/mathiasbynens/punycode.js/releases/tag/v2.0.0) marked as `latest`

although `v2.0.0` is not the latest released version.

The releases after `v2.0.0` are not listed under [releases](https://github.com/mathiasbynens/punycode.js/releases).

These are the current v2 tags in the repo:

```text
$ git tag -l v2*
v2.0.0
v2.0.1
v2.1.0
v2.1.1
v2.2.0
v2.2.1
v2.2.2
```

According to npm, the latest release to the npm registry is `punycode@2.3.0`

```text
$ npm view punycode.js dist-tags
{ latest: '2.3.0' }
```

## Suggestions

1. Add a tag `v2.3.0` to https://github.com/mathiasbynens/punycode.js/commit/2047fe7e4ddcece709b388a569be51c62045535e and mark it in GitHub as the latest release
2. Mark the following tags as released in GitHub
    ```text
    v2.0.1
    v2.1.0
    v2.1.1
    v2.2.0
    v2.2.1
    v2.2.2
    ```

See GitHub docs [Managing releases in a repository](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

**Comment by mathiasbynens** [comment]
Thanks! I ran `git tag v2.3.0 2047fe7e4ddcece709b388a569be51c62045535e && git push --tags`. I’ll leave this open to deal with the other tags.

**Comment by MikeMcC399** [comment]
@mathiasbynens 

Thanks for picking this up! I see you've also released `v2.3.1` so the original post is no longer exactly accurate although the general principle still applies.

**Comment by MikeMcC399** [comment]
## Current state

| [Tag](https://github.com/mathiasbynens/punycode.js/tags)      | Listed in [Releases](https://github.com/mathiasbynens/punycode.js/releases) |
| -------- | --------------------------------------------------------------------------- |
| `v2.0.0` | YES                                                                         |
| `v2.0.1` |
| `v2.1.0` |
| `v2.1.1` |
| `v2.2.0` |
| `v2.2.1` |
| `v2.2.2` |
| `v2.3.0` |
| `v2.3.1` | YES                                                                         |

**Comment by MikeMcC399** [comment]
@mathiasbynens 

If you are not planning to add the intermediate releases from `v2.0.1` to `v2.3.0` inclusive to the https://github.com/mathiasbynens/punycode.js/releases page, then I guess we can close this issue.

**Comment by mathiasbynens** [comment]
Hi Mike, thanks for your patience. The missing releases should be added now.

**Comment by MikeMcC399** [comment]
Hi @mathiasbynens 

> The missing releases should be added now.

Thank you for resolving this issue!
